services:
  - type: web
    name: kimekime-bbs
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
